import type { Lead, User } from './types'

export const mockUsers: User[] = [
  { id: '1', name: 'Lucas Silva', email: 'lucas@sdr.ai', avatar: '' },
  { id: '2', name: 'Maria Santos', email: 'maria@sdr.ai', avatar: '' },
  { id: '3', name: 'Pedro Oliveira', email: 'pedro@sdr.ai', avatar: '' },
  { id: '4', name: 'Ana Costa', email: 'ana@sdr.ai', avatar: '' },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Carlos Mendes',
    email: 'carlos@techcorp.com',
    phone: '(11) 99999-1111',
    company: 'TechCorp Brasil',
    role: 'Diretor de TI',
    stage: 'qualificado',
    origin: 'LinkedIn',
    notes: 'Interessado em automacao de vendas',
    assignedTo: '1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Juliana Ferreira',
    email: 'juliana@startup.io',
    phone: '(21) 99999-2222',
    company: 'Startup.io',
    role: 'CEO',
    stage: 'reuniao_agendada',
    origin: 'Inbound',
    notes: 'Reuniao marcada para proxima semana',
    assignedTo: '1',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'Roberto Almeida',
    email: 'roberto@bigcorp.com.br',
    phone: '(11) 99999-3333',
    company: 'BigCorp',
    role: 'Gerente Comercial',
    stage: 'tentando_contato',
    origin: 'Outbound',
    assignedTo: '2',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '4',
    name: 'Fernanda Lima',
    email: 'fernanda@industria.com',
    company: 'Industria SA',
    role: 'Diretora Comercial',
    stage: 'proposta_enviada',
    origin: 'Evento',
    notes: 'Conheceu no evento de vendas B2B',
    assignedTo: '1',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '5',
    name: 'Marcos Souza',
    email: 'marcos@varejo.com',
    phone: '(31) 99999-5555',
    company: 'Varejo Express',
    role: 'Head de Operacoes',
    stage: 'lead_mapeado',
    origin: 'Site',
    assignedTo: '3',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'Patricia Gomes',
    email: 'patricia@consultoria.com',
    company: 'Consultoria Prime',
    role: 'Socia',
    stage: 'base',
    origin: 'Indicacao',
    assignedTo: '2',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '7',
    name: 'Ricardo Barbosa',
    email: 'ricardo@logistica.com.br',
    phone: '(41) 99999-7777',
    company: 'Logistica Total',
    role: 'Diretor de Logistica',
    stage: 'ganho',
    origin: 'LinkedIn',
    notes: 'Cliente fechado! Contrato assinado',
    assignedTo: '1',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '8',
    name: 'Camila Rodrigues',
    email: 'camila@fintech.com',
    company: 'Fintech Solutions',
    role: 'CPO',
    stage: 'contato_realizado',
    origin: 'Outbound',
    notes: 'Primeiro contato realizado, aguardando retorno',
    assignedTo: '4',
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-21'),
  },
]
